### ISSUE TITLE
Transformando a classe em um pacote PHP do Composer

### ISSUE THREAD

**Issue by filhocodes** [gigapix/frete-correios#1]
Levantei alguns pontos que podem ser feitos:

**Projeto:**
- [x] Transformar a classe em uma biblioteca composer (#2)
- [ ] Criar testes unitários
- [x] Seguir o padrão PSR2, utilizando o PHPCS para identificar erros (#2)

**Classe:**
- [x] Utilizar nomes significativos nos métodos e variáveis (#2)
- [x] Utilizar o construtor como único ponto de injeção da classe (#2)
- [x] Transformar todas as mensagens de erro em `Exception`s (#2)
- [x] Trocar o `file_get_contents` por uma requisição via `cURL` ou a biblioteca [`Requests`](https://github.com/rmccue/Requests) para tratar erros na requisição HTTP (#4)

**Exemplo:**
- [x] Exibir mensagens de erro quando houver (#2)

**Documentação:**
- [x] Disponibilizar documentação do código (PHPDoc)
- [ ] Instruções de como utilizar a biblioteca no seu projeto

**Melhorias (a discutir)**
- Transformar a coleção de produtos, atualmente em array, em objetos (`ListaProdutos` e `Produto`, ou um array de objetos `Produto`, ou interfaces, por exemplo), para facilitar a validação dos dados do produto e facilitar a integração com projetos diversos.

**Comment by gabsprates** [comment]
Não escrevi exatamente uma documentação, mas expliquei como funciona o cálculo de frete.
Assim que possível, coloco instruções.
- [x] Disponibilizar documentação do código (PHPDoc)
  [README.md](https://github.com/gigapix/freteCorreios/blob/master/README.md)

**Comment by filhocodes** [comment]
:+1:

Ficou bem explicativo. Pra mim, só falta instruções de como usar a biblioteca/classe pra completar o README. Ficou bacana d+!
